name: Created
version: 1.0.0
description: Save a timestamp when the content is created
url: https://github.com/jrc9designstudio/statamic-created
developer: JRC9 Design Studio
developer_url: https://jrc9.ca
